# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.0
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mongo:4.0.3
        # command: mongod --replSet tweetoo --logpath "0.log" --dbpath mongodb/rs0-0 --port 27017  &
        #          mongod --replSet tweetoo --logpath "1.log" --dbpath mongodb/rs0-1 --port 27018  &
        #          mongod --replSet tweetoo --logpath "2.log" --dbpath mongodb/rs0-2 --port 27019  &

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: 'Installing npm dependencies'
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run:
          name: 'Testing CRUD operations'
          command: npm run test-crud

      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml